# k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: iris-service
  namespace: iris-app
spec:
  selector:
    app: iris-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

